const products = [
  {
    name: "Wireless Bluetooth Headphones",
    brand: "Sony",
    category: "Electronics",
    price: 8990,
    stock: 25,
    rating: 4.8,
    numReviews: 156,
    description: "Noise-canceling over-ear wireless headphones.",
    image: "https://example.com/images/headphones.jpg",
  },
  {
    name: "iPhone 15 Pro",
    brand: "Apple",
    category: "Smartphones",
    price: 149999,
    stock: 12,
    rating: 4.9,
    numReviews: 312,
    description: "Apple iPhone 15 Pro with A17 Pro chip.",
    image: "https://example.com/images/iphone15pro.jpg",
  },
  {
    name: "Galaxy S25",
    brand: "Samsung",
    category: "Smartphones",
    price: 129999,
    stock: 18,
    rating: 4.7,
    numReviews: 201,
    description: "Samsung flagship Android smartphone.",
    image: "https://example.com/images/galaxys25.jpg",
  },
  {
    name: "Gaming Laptop",
    brand: "ASUS",
    category: "Computers",
    price: 185000,
    stock: 8,
    rating: 4.8,
    numReviews: 74,
    description: "High-performance gaming laptop with RTX graphics.",
    image: "https://example.com/images/laptop.jpg",
  },
  {
    name: "Mechanical Keyboard",
    brand: "Keychron",
    category: "Accessories",
    price: 8500,
    stock: 40,
    rating: 4.6,
    numReviews: 120,
    description: "RGB mechanical keyboard with hot-swappable switches.",
    image: "https://example.com/images/keyboard.jpg",
  },
  {
    name: "Wireless Mouse",
    brand: "Logitech",
    category: "Accessories",
    price: 4200,
    stock: 65,
    rating: 4.7,
    numReviews: 240,
    description: "Ergonomic wireless mouse with long battery life.",
    image: "https://example.com/images/mouse.jpg",
  },
  {
    name: "4K Smart TV 55-inch",
    brand: "LG",
    category: "Electronics",
    price: 89999,
    stock: 10,
    rating: 4.8,
    numReviews: 89,
    description: "Ultra HD Smart TV with HDR support.",
    image: "https://example.com/images/tv.jpg",
  },
  {
    name: "Running Shoes",
    brand: "Nike",
    category: "Fashion",
    price: 11990,
    stock: 50,
    rating: 4.5,
    numReviews: 175,
    description: "Comfortable running shoes for daily training.",
    image: "https://example.com/images/shoes.jpg",
  },
  {
    name: "Smart Watch",
    brand: "Apple",
    category: "Wearables",
    price: 45999,
    stock: 22,
    rating: 4.8,
    numReviews: 144,
    description: "Fitness tracking and health monitoring smartwatch.",
    image: "https://example.com/images/watch.jpg",
  },
  {
    name: "Portable Bluetooth Speaker",
    brand: "JBL",
    category: "Audio",
    price: 7999,
    stock: 35,
    rating: 4.7,
    numReviews: 98,
    description: "Waterproof portable Bluetooth speaker.",
    image: "https://example.com/images/speaker.jpg",
  },
  {
    name: "DSLR Camera",
    brand: "Canon",
    category: "Photography",
    price: 99999,
    stock: 7,
    rating: 4.8,
    numReviews: 65,
    description: "Professional DSLR camera for photography.",
    image: "https://example.com/images/camera.jpg",
  },
  {
    name: "Air Fryer",
    brand: "Philips",
    category: "Home Appliances",
    price: 14999,
    stock: 20,
    rating: 4.6,
    numReviews: 112,
    description: "Healthy cooking with rapid air technology.",
    image: "https://example.com/images/airfryer.jpg",
  },
  {
    name: "Coffee Maker",
    brand: "DeLonghi",
    category: "Kitchen",
    price: 24999,
    stock: 14,
    rating: 4.7,
    numReviews: 57,
    description: "Automatic coffee maker with milk frother.",
    image: "https://example.com/images/coffeemaker.jpg",
  },
  {
    name: "Office Chair",
    brand: "IKEA",
    category: "Furniture",
    price: 18999,
    stock: 30,
    rating: 4.5,
    numReviews: 87,
    description: "Ergonomic office chair with lumbar support.",
    image: "https://example.com/images/chair.jpg",
  },
  {
    name: "Backpack",
    brand: "American Tourister",
    category: "Bags",
    price: 3499,
    stock: 60,
    rating: 4.4,
    numReviews: 136,
    description: "Water-resistant travel backpack.",
    image: "https://example.com/images/backpack.jpg",
  },
  {
    name: "Men's Casual T-Shirt",
    brand: "Levi's",
    category: "Fashion",
    price: 1999,
    stock: 100,
    rating: 4.3,
    numReviews: 250,
    description: "100% cotton casual t-shirt.",
    image: "https://example.com/images/tshirt.jpg",
  },
  {
    name: "Women's Handbag",
    brand: "Michael Kors",
    category: "Fashion",
    price: 17999,
    stock: 15,
    rating: 4.7,
    numReviews: 71,
    description: "Premium leather handbag.",
    image: "https://example.com/images/handbag.jpg",
  },
  {
    name: "Mountain Bike",
    brand: "Giant",
    category: "Sports",
    price: 69999,
    stock: 6,
    rating: 4.8,
    numReviews: 39,
    description: "21-speed mountain bicycle.",
    image: "https://example.com/images/bike.jpg",
  },
  {
    name: "Electric Toothbrush",
    brand: "Oral-B",
    category: "Personal Care",
    price: 5999,
    stock: 45,
    rating: 4.6,
    numReviews: 82,
    description: "Rechargeable electric toothbrush.",
    image: "https://example.com/images/toothbrush.jpg",
  },
  {
    name: "Yoga Mat",
    brand: "Adidas",
    category: "Fitness",
    price: 2999,
    stock: 80,
    rating: 4.5,
    numReviews: 101,
    description: "Non-slip yoga mat for home workouts.",
    image: "https://example.com/images/yogamat.jpg",
  },
    {
    name: "MacBook Air M3",
    brand: "Apple",
    category: "Electronics",
    price: 189999,
    stock: 15,
    rating: 4.9,
    numReviews: 342,
    description: "13-inch MacBook Air powered by the Apple M3 chip.",
    image: "https://example.com/images/macbook-air-m3.jpg",
  },
  {
    name: "iPad Air 13",
    brand: "Apple",
    category: "Electronics",
    price: 109999,
    stock: 20,
    rating: 4.8,
    numReviews: 184,
    description: "13-inch iPad Air with M2 chip and Liquid Retina display.",
    image: "https://example.com/images/ipad-air.jpg",
  },
  {
    name: "PlayStation 5 Slim",
    brand: "Sony",
    category: "Electronics",
    price: 74999,
    stock: 12,
    rating: 4.9,
    numReviews: 528,
    description: "Next-generation gaming console with ultra-fast SSD.",
    image: "https://example.com/images/ps5-slim.jpg",
  },
  {
    name: "Nintendo Switch OLED",
    brand: "Nintendo",
    category: "Electronics",
    price: 48999,
    stock: 18,
    rating: 4.8,
    numReviews: 267,
    description: "Portable gaming console with a vibrant OLED display.",
    image: "https://example.com/images/nintendo-switch-oled.jpg",
  },
  {
    name: "Dyson V15 Detect",
    brand: "Dyson",
    category: "Electronics",
    price: 94999,
    stock: 10,
    rating: 4.7,
    numReviews: 138,
    description: "Cordless vacuum cleaner with laser dust detection.",
    image: "https://example.com/images/dyson-v15.jpg",
  },
  {
    name: "GoPro HERO13 Black",
    brand: "GoPro",
    category: "Electronics",
    price: 69999,
    stock: 14,
    rating: 4.8,
    numReviews: 196,
    description: "Waterproof 5.3K action camera with advanced stabilization.",
    image: "https://example.com/images/gopro-hero13.jpg",
  },
  {
    name: "Kindle Paperwhite",
    brand: "Amazon",
    category: "Electronics",
    price: 22999,
    stock: 30,
    rating: 4.7,
    numReviews: 421,
    description: "Waterproof e-reader with a high-resolution glare-free display.",
    image: "https://example.com/images/kindle-paperwhite.jpg",
  },
];

const topElectronicsProducts = products
.filter(item => item.category === "Electronics")
.sort((a, b) => b.rating - a.rating)
.slice(0, 3)
.map(item => ({productName: item.name}))

console.log(topElectronicsProducts)